#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

xsetroot -cursor_name left_ptr &
bspc config border_width         1
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Floating terminal
function half_dimension() {
	local width=$(($(bspc query -T -m "$1" | jq -r '.rectangle | .width')/2))
	local height=$(($(bspc query -T -m "$1" | jq -r '.rectangle | .height')/2))
	echo "${width}x${height}"
}
bspc rule -a floating_kitty state=floating rectangle=$(half_dimension $(bspc query -M --names | head -n 1))+0+0 center=true

# Floating calculator
bspc rule -a Galculator state=floating

# Firefox rules
# Picture-in-picture floating
bspc rule -a 'firefox:Toolkit:Picture-in-Picture' state=floating
# Downloads floating
bspc rule -a 'firefox:Places:*' state=floating

# Wallpaper
nitrogen --restore &

# Top bar
$HOME/.config/polybar/launch.sh --shapes

# Clipboard history
greenclip daemon &

