#!/bin/sh

# Check if bspwm is running:
pgrep bspwm > /dev/null || exit 0

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Setup the monitors
# This resets the monitors properly every time bspwm is reloaded
# And also creates the desktops with names based on the monitor
~/.config/bspwm/monitor_setup.sh &

xsetroot -cursor_name left_ptr &
bspc config border_width         3
bspc config window_gap           0
bspc config active_border_color  "#585b70"
bspc config focused_border_color "#cce8aa"
bspc config normal_border_color  "#1e1e2e"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

function half_dimension() {
	local width=$(($(bspc query -T -m "$1" | jq -r '.rectangle | .width')/2))
	local height=$(($(bspc query -T -m "$1" | jq -r '.rectangle | .height')/2))
	echo "${width}x${height}"
}

# Floating rules
bspc rule -a floating_kitty state=floating rectangle=$(half_dimension $(bspc query -M --names | head -n 1))+0+0 center=true
bspc rule -a '*:Toolkit:Picture-in-Picture' state=floating sticky=on focus=on
# bspc rule -a 'firefox:Places:*' state=floating # Firefox Downloads
bspc rule -a 'thunderbird:Msgcompose' state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a ripdrag state=floating
bspc rule -a 'com.ra4king.circuitsim.gui.CircuitSim:*:Rename circuit' state=floating

# Tiling rules
# Zathura
bspc rule -a Zathura state=tiled

# Autostart
# Policy Kit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Bar
$HOME/.config/polybar/launch.sh &
# Wallpaper
nitrogen --restore &
# Compositor
picom &
# Gestures
libinput-gestures-setup stop start &
# Notifications
pkill -9 dunst; dunst &
# IME/IMF
fcitx5 -r &
# Clipboard history
pkill -9 greenclip; greenclip daemon &
# Auto-suspend
pkill -9 xautolock
# xautolock -time 60 -locker 'systemctl suspend' -notify 30 -notifier 'notify-send "Inactivity detected" "Suspending in 30 seconds."' -detectsleep &

