#!/bin/sh

# Check if bspwm is running:
pgrep bspwm > /dev/null || exit 0

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Setup the monitors
# This resets the monitors properly every time bspwm is reloaded
# And also creates the desktops with names based on the monitor
~/.config/bspwm/monitor_setup.sh

xsetroot -cursor_name left_ptr &
bspc config border_width         1
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Floating terminal
function half_dimension() {
	local width=$(($(bspc query -T -m "$1" | jq -r '.rectangle | .width')/2))
	local height=$(($(bspc query -T -m "$1" | jq -r '.rectangle | .height')/2))
	echo "${width}x${height}"
}
bspc rule -a floating_kitty state=floating rectangle=$(half_dimension $(bspc query -M --names | head -n 1))+0+0 center=true

# Floating calculator
bspc rule -a Galculator state=floating

# Firefox rules
# Picture-in-picture floating
bspc rule -a 'firefox:Toolkit:Picture-in-Picture' state=floating
# Downloads floating
bspc rule -a 'firefox:Places:*' state=floating

# Wallpaper
nitrogen --restore &

# Top bar
$HOME/.config/polybar/launch.sh

# Clipboard history
greenclip daemon &

# Notifications
pkill -9 dunst && dunst &

# Compositor
picom &

