#!/bin/sh

function cdb () {
	local dir=~/.scripts

	if  [ ! -e "$dir"/.cd_bookmarks ] ; then
		mkdir "$dir"/.cd_bookmarks
	fi

	local cwd="${PWD##*/}"
	if (( $# == 0 )); then
		if [ ! -f "$dir"/.cd_bookmarks/"$cwd" ] ; then
			echo "cd `pwd`" > "$dir"/.cd_bookmarks/"$cwd"
		else
			echo "Try again! Looks like there is already a bookmark '$cwd'"
		fi
		return
	fi

	case $1 in
		-d) shift
			if [ -f "$dir"/.cd_bookmarks/$1 ] ; then
				rm "$dir"/.cd_bookmarks/"$1"
			else
				echo "Oops, forgot to specify the bookmark"
			fi
			;;
		-l)
			ls "$dir"/.cd_bookmarks -A
			;;
		-n)
			echo "cd `pwd`" > "$dir"/.cd_bookmarks/"$cwd"
			;;
		*)
			if [ -f "$dir"/.cd_bookmarks/"$1" ] ; then
				source "$dir"/.cd_bookmarks/"$1"
			else
				echo "Hmm...it looks like this bookmark does not exist"
			fi
			;;
	esac
}
