#!/bin/zsh

function cdb() {
	local dir=~/.scripts

	if  [ ! -e "$dir"/.cd_bookmarks ] ; then
		mkdir "$dir"/.cd_bookmarks
	fi

	local cwd="${PWD##*/}"
	if (( $# == 0 )); then
		if [ ! -f "$dir"/.cd_bookmarks/"$cwd" ] ; then
			echo "`pwd`" > "$dir"/.cd_bookmarks/"$cwd"
		else
			echo "Try again! Looks like there is already a bookmark '$cwd'"
		fi
		return
	fi

	case $1 in
		-d) shift
			local to_rm="$1"
			if (($# == 0)); then
				to_rm=$cwd
			fi
			if [ -f "$dir"/.cd_bookmarks/"$to_rm" ] ; then
				rm "$dir"/.cd_bookmarks/"$to_rm"
			else
				echo "Hmm...it looks like this bookmark does not exist"
			fi
			;;
		-l)
			ls "$dir"/.cd_bookmarks -A
			;;
		*)
			if [ -f "$dir"/.cd_bookmarks/"${1%%/*}" ] ; then
				cd "$(cat "$dir"/.cd_bookmarks/"${1%%/*}")/${1#*/}"
			else
				echo "Hmm...it looks like this bookmark does not exist"
			fi
			;;
	esac
}

# Autocomplete
_cdb () {
	# undefined
	builtin autoload -XUz /usr/share/zsh/site-functions
}

