#!/bin/zsh

case $1 in
	-f) # Show full log
		cat /home/arcwand/.window_log
		;;
	-d) # Show previous day
		tail -n 86400 /home/arcwand/.window_log
		;;
	-u) # Show only unique windows from the last day
		tail -n 86400 /home/arcwand/.window_log | sed 's/^....-..-.. ..:.. | //' | sort | uniq -c | sort -n
		;;
	*) # Default behavior
		cat /home/arcwand/.window_log
		;;
esac
